name: Feature Request
description: Suggest a new tool or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Describe the use case or limitation you're hitting.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe what you'd like to see implemented.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any workarounds or alternative approaches you've thought about.

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - New MCP tool
        - Existing tool improvement
        - Performance / reliability
        - Docker / deployment
        - Documentation
        - Other
    validations:
      required: true
